version: "3.7"

networks:
  frappe-network:
    name: frappe-network
    external: true

volumes:
  frappe15-mariadb-vol:
    external: true
    name: frappe15-mariadb-vol
  frappe15-redis-cache-data:
    external: true
    name: frappe15-redis-cache-data
  frappe15-redis-queue-data:
    external: true
    name: frappe15-redis-queue-data
  frappe15-redis-socketio-data:
    external: true
    name: frappe15-redis-socketio-data
  # postgresql-vol:

services:
  mariadb:
    image: mariadb:10.6
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-character-set-client-handshake
      - --skip-innodb-read-only-compressed # Temporary fix for MariaDB 10.6
      - --max_allowed_packet=512M
    environment:
        MYSQL_ROOT_PASSWORD: 123
        MYSQL_ROOT_USER: root
    volumes:
      - frappe15-mariadb-vol:/var/lib/mysql
    networks:
      - frappe-network
    ports:
      - "33066:3306"

  # Enable PostgreSQL only if you use it, see development/README.md for more information.
  # postgresql:
  #   image: postgres:11.8
  #   restart: on-failure
  #   environment:
  #     - POSTGRES_PASSWORD=123
  #   volumes:
  #     - postgresql-vol:/var/lib/postgresql/data

  redis-cache:
    image: redis:alpine
    volumes:
      - frappe15-redis-cache-data:/data
    networks:
      - frappe-network

  redis-queue:
    image: redis:alpine
    volumes:
      - frappe15-redis-queue-data:/data
    networks:
      - frappe-network

  redis-socketio:
    image: redis:alpine
    volumes:
      - frappe15-redis-socketio-data:/data
    networks:
      - frappe-network

  frappe:
    build: .
    command: sleep infinity
    user: frappe:frappe
    environment:
      SSH_AUTH_SOCK: $SSH_AUTH_SOCK
    volumes:
      - ../../frappe_docker_dev:/workspace
      - /home/${USER}/.ssh/known_hosts:/home/frappe/.ssh/known_hosts
      - /home/${USER}/.bash_history:/home/frappe/.bash_history
      - /home/${USER}/.gitconfig:/home/frappe/.gitconfig
      - .bash_aliases:/home/frappe/.bash_aliases
      - $SSH_AUTH_SOCK:$SSH_AUTH_SOCK
    working_dir: /workspace/development/
    ports:
      - "8000-8005:8000-8005"
      - "9000-9005:9000-9005"
      - "587:587"
      - "143:143"
    networks:
      - frappe-network

  # adminer:
  # image: adminer
  # depends_on:
  # - mariadb
  # ports:
  # - 7000:8080
  # networks:
  # - frappe-network
